#!/bin/sh

Replace(){
echo "Fetching Mettke's keys..."
sudo pacman-key --recv 7448C890582975CD
sudo pacman-key --lsign 7448C890582975CD
echo "Recieved Mettke's keys"
echo
echo "Fetching Reborn's keys..."
wget https://repo.itmettke.de/Reborn-OS/rebornos-keyring-20180302-1-any.pkg.tar.xz
wget https://repo.itmettke.de/Reborn-OS/rebornos-keyring-20180302-1-any.pkg.tar.xz.sig
sudo pacman -U rebornos-keyring-20180302-1-any.pkg.tar.xz --noconfirm
echo "Recieved Reborn's keys"
echo
echo "Writing changes to pacman.conf..."
sudo mv /tmp/pacman.conf1 /etc/pacman.conf
sudo pacman -Syy
echo "DONE"
sudo rm rebornos-keyring-20180302-1-any.pkg.tar.xz && rm rebornos-keyring-20180302-1-any.pkg.tar.xz.sig
}

Adding(){
echo "Fetching Mettke's keys..."
sudo pacman-key --recv 7448C890582975CD
sudo pacman-key --lsign 7448C890582975CD
echo "Recieved Mettke's keys"
echo
echo "Fetching Reborn's keys..."
wget https://repo.itmettke.de/Reborn-OS/rebornos-keyring-20180302-1-any.pkg.tar.xz
wget https://repo.itmettke.de/Reborn-OS/rebornos-keyring-20180302-1-any.pkg.tar.xz.sig
sudo pacman -U rebornos-keyring-20180302-1-any.pkg.tar.xz --noconfirm
echo "Recieved Reborn's keys"
echo
echo "Writing changes to pacman.conf..."
sudo mv /tmp/pacman.conf2 /etc/pacman.conf
sudo pacman -Syy
echo "DONE"
sudo rm rebornos-keyring-20180302-1-any.pkg.tar.xz && rm rebornos-keyring-20180302-1-any.pkg.tar.xz.sig
}

Secure(){
echo "Fetching Reborn's keys..."
wget https://repo.itmettke.de/Reborn-OS/rebornos-keyring-20180302-1-any.pkg.tar.xz
wget https://repo.itmettke.de/Reborn-OS/rebornos-keyring-20180302-1-any.pkg.tar.xz.sig
sudo pacman -U rebornos-keyring-20180302-1-any.pkg.tar.xz --noconfirm
echo "Recieved Reborn's keys"
echo
echo "Writing changes to pacman.conf..."
sudo mv /tmp/pacman.conf3 /etc/pacman.conf
sudo pacman -Syy
sudo rm rebornos-keyring-20180302-1-any.pkg.tar.xz && rm rebornos-keyring-20180302-1-any.pkg.tar.xz.sig
echo "DONE"
}

Unnecessary(){
pacman -Qqtd > /tmp/package-files.txt
yad --title "Unnecessary Packages" --skip-taskbar --form --center --text-align=center --width=300 --height=100 \
--text="Remove clutter with ease" \
--field="View Unnecessary Packages In Terminal:fbtn" "xterm -e nano /tmp/package-files.txt" \
--field="Remove All Unnecessary Packages:fbtn" "xterm -e sudo pacman -Rs $(pacman -Qqdt) --noconfirm" \
--button="Back":1
rm /tmp/package-files.txt
}

Update(){
if [ -f /usr/bin/octopi ]; then
octopi
fi

if [ -f /usr/bin/pamac-updater ]; then
pamac-updater
fi
}

Journal(){
journalctl --vacuum-time=3d && sync
Notice

}

Cache(){
pacman -Scc --noconfirm
Notice

}

Clean(){
paccache -ruk0
Notice

}

Notice()
{
yad --center --width=150 --height=30 --skip-taskbar --undecorated --no-buttons --form --timeout="1" --text-align=center --title="Reborn Maintenance" \
--text="DONE!" \

}

Save()
{
SAVING=$(sed '1q;d' /tmp/saving.txt)
echo "Saving Files To $SAVING"
sudo pacman -Qqen > $SAVING/packages-repository.txt
sudo pacman -Qqem > $SAVING/packages-AUR.txt
echo "Done"
}

Recover()
{
SAVING=$(sed '1q;d' /tmp/saving.txt)
echo "Recovering Files From $SAVING..."
sudo pacman --needed -S - < $SAVING/packages-repository.txt --noconfirm
cat $SAVING/packages-AUR.txt | xargs yaourt -S --needed --noconfirm
echo "Done"
}

StartHere()
{

echo "Setting Directory..."
yad --center --width=350 --height=100 --form --separator='' --title="Reborn Recovery" --save --field="Save To:":CDIR >> /tmp/saving.txt
SAVING=$(sed '1q;d' /tmp/saving.txt)
echo "Using $SAVING Directory"
Next
}

Grub()
{
sudo os-prober
sudo grub-mkconfig -o /boot/grub/grub.cfg
}

Downgrading()
{

echo "Setting Package..."
yad --center --width=300 --height=30 --form --separator='' --title="Reborn Repair" --save --field="Package Name:" >> /tmp/packaging.txt
SAVED=$(sed '1q;d' /tmp/packaging.txt)
echo "Using $SAVED Package"
After
}

After()
{

SAVED=$(sed '1q;d' /tmp/packaging.txt)

yad --form --center --title "Reborn Repair" --width=400 \
--field="Selected Package::RO" "$SAVED" \
--field='Downgrade package:FBTN' "xterm -e downgrade $SAVED" \
--button='gtk-quit:1'
rm /tmp/packaging.txt

}

Next()
{

SAVING=$(sed '1q;d' /tmp/saving.txt)

yad --form --center --title "Reborn Recovery" --width=400 \
--field="Folder to Save Package Lists To::RO" "$SAVING" \
--field='Create Package List:FBTN' '@bash -c "Save"' \
--field='Recover Packages From List:FBTN' 'xterm -e "Recover"' \
--button='gtk-quit:1'
rm /tmp/saving.txt

}

Removing()
{

echo "Setting Package..."
yad --center --width=300 --height=30 --form --separator='' --title="Reborn Repair" --save --field="Package to Remove:" >> /tmp/packaging2.txt
SAVED=$(sed '1q;d' /tmp/packaging2.txt)
echo "Will Remove $SAVED Package"
Removed
}

Removed()
{

SAVED=$(sed '1q;d' /tmp/packaging2.txt)

yad --form --center --title "Reborn Repair" --width=400 \
--field="Selected Package::RO" "$SAVED" \
--field='Remove Package:FBTN' "xterm -e sudo pacman -Rdd $SAVED --noconfirm" \
--button='gtk-quit:1'
rm /tmp/packaging2.txt

}

export -f Replace Adding Secure Unnecessary Update Journal Cache Clean Save Recover StartHere Next Notice Grub Downgrading After Removing Removed


yad --plug=23456 --tabnum=1 --form --columns=2 --center --text-align=center \
--text="The following applications are available for install:" \
--field='Wine!!'"Easily run several Windows programs on Linux - safely. Wine offers a simple, non-technical method of installing Windows software. Simply download the desired .exe file like you normally would for Windows, and then right click to run using Wine. It's as easy as that.:fbtn" "xterm -e sudo pacman wine winetricks playonlinux --noconfirm" \
--field='NixNote2!!'"Nixnote, (formerly Nevernote) is an opensource client for Evernote, allowing you to track your digital life in a single, convenient place. NOTE: an Evernote account is required for cloud synchronization.:fbtn" "xterm -e sudo pacman -S nixnote2 --noconfirm" \
--field='Reborn Recovery!!'"Reborn Recovery allows you to save a list of all your installed programs in a file so that you can reinstall them later.:fbtn" "xterm -e sudo pacman -S reborn-recovery --noconfirm" \
--field='Hardinfo!!'"Simple application for hardware analysis and system benchmarking. Through this, you can easily view all of your system specs without having to revert to the commandline.:fbtn" "xterm -e sudo pacman -S hardinfo --noconfirm" &

yad --plug=23456 --tabnum=2 --form --center --text-align=center \
--text="Please consider adding the following to your system:" \
--field="Add Mettke's Repo and Reborn's European Mirror (Recommended for most)!!""Replace BlueStar's Repo with Mettkes Repo, offering more packages as well as faster mirror speeds. In addition, this adds Reborn's new European mirror to your mirrorlist, offering quicker and more reliable download speeds for those in Europe:fbtn" 'xterm -e "Replace"' \
--field="Add Mettke's Repo and Replace Reborn's Mirrors (Recommended for Europeans)!!""Do the same as above, except that when adding the European mirror to Reborn, it replaces the current Github one, allowing Eropean users quicker and more reliable speads.:fbtn" 'xterm -e "Adding"' \
--field="Add Nothing New, Only Upgrade Reborn's Security (Not Recommended)!!""The Reborn Repository now has updated security features available for you. To continue using Reborn OS safely, please upgrade them now. Thanks!:fbtn" 'xterm -e "Secure"' &

yad --plug=23456 --tabnum=3 --form --title="System Maintenance" --center --text-align=center --columns=2 \
--text="A few simple commands to keep Reborn working flawlessly and your system clean" \
--field="Clear Cache:fbtn" '@bash -c "Cache"' \
--field="Clean Journal:fbtn" '@bash -c "Journal"' \
--field="Clean Built Packages:fbtn" '@bash -c "Clean"' \
--field="Rank Mirrors:fbtn" "xterm -e sudo reflector --verbose --age 8 --fastest 128 --latest 64 --number 32 --sort rate --save /etc/pacman.d/mirrorlist" \
--field="Unnecessary Packages:fbtn" '@bash -c "Unnecessary"' \
--field="Update System:fbtn" '@bash -c "Update"' &

yad --plug=23456 --tabnum=4 --form --title="System Repair" --center --text-align=center --columns=2 \
--text="A few simple steps to prevent Reborn from disaster and nurse it back to health" \
--field="Save / Recover Programs:fbtn" '@bash -c "StartHere"' \
--field="Rebuild Grub:fbtn" 'xterm -e "Grub"' \
--field="Reinstall Grub (EFI):fbtn" "xterm -e grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Reborn-Grub" \
--field="Downgrade:fbtn" '@bash -c "Downgrading"' \
--field="Remove Package (Leaving Dependencies):fbtn" '@bash -c "Removing"' \
--field="Ask Actual Humans on the Forum:fbtn" "@bash -c xdg-open https://rebornos.freeforums.net" &

yad --notebook --center --key=23456 --tab="New Applications" --tab="Repositories" --tab="Maintenance" --tab="Repair" --button=gtk-quit:1 \
--title="Reborn Improvements" \
